ZeppelinBot/Zeppelin

src/plugins/Utility.ts
This should in theory make !search ignore leading white spaces that cause no results to be found since it is taken into the equation.
I might have missed a spot but i am pretty sure this is the only place where we work with the search query
=> Fix leading white-space resulting in no results

backend/src/plugins/Utility.ts
Since -i means 'ignore case', the current code flips the meaning of the "case-sensitive" arg. A 'true' value would make the search case insensitive, while a false or undefined value (default) would make the search case sensitive. This PR reverses the ternary statement to be in the right order
=> fixed search case sensitivity issue

dashboard/src/components/docs/Plugin.vue
The / separating the aliases was right behind every alias without a space.
The original command had a space behind it
=> Fix spacing issue for aliases

backend/src/plugins/WelcomeMessage/events/SendWelcomeMessageEvt.ts
=> Fix failed DM welcome messages sending the log undefined#undefined

backend/src/plugins/Utility.ts
This pull requests add the aliases "purge" and "prune" to the clean command in the utility plugin.
=> utility: add aliases for clean command

backend/src/plugins/ModActions/commands/CasesModCmd.ts, backend/src/plugins/ModActions/commands/CasesUserCmd.ts
Wanted to add !modlogs as an alias to !cases because I've been getting a lot of requests for that
=> Feature: Adding modlogs as an alias to the cases commands

backend/src/plugins/Tags/TagsPlugin.ts, backend/src/plugins/Tags/types.ts, backend/src/plugins/Tags/util/onMessageCreate.ts
Includes config preprocessor to only allow either `delete_with_command` or `xyz_delete_invoke`, never both (Both globally and for every category).
Falls back to `delete_with_command` in case delete_with_command is enabled in an override.
=> Allow automatic tag invoke deletion

backend/src/plugins/Tags/TagsPlugin.ts
Previously wouldn't match mentions, but would match `<@#!&[id]>`. Now matches mentions (user, role, or channel) correctly.
=> Correct mention regex in mention tag function

backend/src/plugins/WelcomeMessage/events/SendWelcomeMessageEvt.ts
Explicit user so you dont have to use member.user.var
Guild object so you can include things like member count, even though they might not be 100% accurate all the time
=> Add user and guild objects to WelcomeMessage formatting

backend/src/plugins/Mutes/MutesPlugin.ts, backend/src/plugins/Mutes/functions/muteUser.ts, backend/src/plugins/Mutes/types.ts
If any non-id string is entered in `move_to_voice_channel`, the user is kicked from the VC instead of being moved. We do not automatically kick if the option is set to null in order to not make this a breaking change for old, intended behavior
=> Allow kicking the user from VC on mute

backend/src/plugins/Tags/TagsPlugin.ts, backend/src/plugins/Tags/types.ts, backend/src/plugins/Tags/util/onMessageCreate.ts
Checked when a tag is posted - so a tag can have for example pings enabled if a mod executes that tag, but not if anyone below mod does it.
=> Add allow_mentions option to enable tags mentioning users and roles

backend/src/plugins/ModActions/commands/AddCaseCmd.ts, backend/src/plugins/ModActions/commands/BanCmd.ts, backend/src/plugins/ModActions/commands/ForcebanCmd.ts, backend/src/plugins/ModActions/commands/UnbanCmd.ts, backend/src/plugins/ModActions/commands/WarnCmd.ts, backend/src/plugins/ModActions/functions/actualKickMemberCmd.ts, backend/src/plugins/ModActions/functions/actualMuteUserCmd.ts, backend/src/plugins/ModActions/functions/actualUnmuteUserCmd.ts
Previously the message was "No permission for -mod" which is a bit ambiguous, and could suggest that the bot doesn't have permission which doesn't make much sense, so I've changed it to "You don't have permission to use -mod" to better convey it's the command author who lacks the required permissions.
=> chore: update wording of permission error for -mod

backend/src/plugins/Automod/AutomodPlugin.ts, backend/src/plugins/Automod/actions/ban.ts, backend/src/plugins/Automod/actions/kick.ts, backend/src/plugins/Automod/actions/mute.ts, backend/src/plugins/Automod/actions/warn.ts, backend/src/plugins/Automod/events/runAutomodOnModAction.ts, backend/src/plugins/Automod/triggers/ban.ts, backend/src/plugins/Automod/triggers/kick.ts, backend/src/plugins/Automod/triggers/mute.ts, backend/src/plugins/Automod/triggers/warn.ts, backend/src/plugins/Automod/types.ts, backend/src/plugins/ModActions/commands/WarnCmd.ts, backend/src/plugins/ModActions/functions/banUserId.ts, backend/src/plugins/ModActions/functions/kickMember.ts, backend/src/plugins/ModActions/functions/warnMember.ts, backend/src/plugins/ModActions/types.ts, backend/src/plugins/Mutes/functions/muteUser.ts, backend/src/plugins/Mutes/types.ts
New automod options for warn, mute, kick and ban triggers:
```
manual: boolean (true)
automatic: boolean (true)
```
If value is set to true, actions of that nature are allowed. For example, setting manual to false will cause the trigger to only return true if the action was taken by automod.
=> Allow Automod to distinguish whether or not actions are manual or automatic

backend/src/plugins/ModActions/commands/CasesUserCmd.ts
It is also possible to reverse the filters using the -r flag.
Examples:
`!cases 108552944961454080 -m -b` Only shows mutes and bans
`!cases 108552944961454080 -r -m` Shows all types *except* for mutes
=> Allow filtering !cases to certain types using switches

backend/src/plugins/Utility/UtilityPlugin.ts, backend/src/plugins/Utility/commands/EmojiInfoCmd.ts, backend/src/plugins/Utility/commands/InfoCmd.ts, backend/src/plugins/Utility/commands/RoleInfoCmd.ts, backend/src/plugins/Utility/functions/getEmojiInfoEmbed.ts, backend/src/plugins/Utility/functions/getRoleInfoEmbed.ts, backend/src/plugins/Utility/types.ts
The role-info command was based on the one from https://github.com/Dragory/ZeppelinBot/pull/116
On the emoji-info command, only custom emojis from the guild the command was run on can be used in the command
=> Added role and emoji info commands

dashboard/src/components/docs/ArgumentTypes.vue
Weeks were missing but [are supported](https://github.com/Dragory/ZeppelinBot/blob/edd78fc9c643a4ba92a21ffc5bd50b8b8e00e448/backend/src/utils.ts#L45)
=> added missing duration format to docs

backend/src/plugins/Tags/TagsPlugin.ts, backend/src/plugins/Tags/util/renderTagBody.ts, backend/src/templateFormatter.ts
New functions:
`isMention` - ~~Returns the mention if given arg is a valid mention, or empty string otherwise~~ [Updated] Returns boolean value of whether the input is a mention (checks format only, not whether user/role/channel exists).
`setr` - Same as `set` but returns `val`. (defaults to empty string if key is not string).
`lower` - Takes a string and returns it all set to lower case. Returns empty string if arg is not a string.
`upper` - Takes a string and returns it all set to upper case. Returns empty string if arg is not a string.
`upperFirst` - Takes a string and returns the same string with the first character uppercase. Returns empty string if arg is not a string.
=> Add various new tag functions

dashboard/src/components/docs/Counters.vue
The docs should say value, instead say amount.
I have thus rectified this critical error, saving users countless hours of pain
=> Counter docs typo

backend/src/plugins/Utility/functions/getInviteInfoEmbed.ts
For whatever reason, `invite.channel` is currently `null` for these invites, I assume it's a issue with DJS not parsing the type correctly.
For the time being (and for future-proofing) we should check if `channel` exists.
Invite Sample : `9A55gsSJDZ`
Issue reported by BanTheNons#8297 on discord (460478012794863637)
=> DJS Temporary fix for school hub invites

backend/src/utils.ts
Graphic on discord pointed out this new bypass, just updating the regex.
`https://discord.com/friend-invite/code#`
Also, currently automod will double-trigger invite (and probably others as well) filters due to embeds (message update), even if the violation is the exact same. I'm not sure what the best fix and impl is here, so I won't write up anything, but in theory I imagine it would have to be either checking message content is the exact same on msg update, or just ignoring duplicate violations on the same filter for the same data (i.e. if alrd flagged invite code `1234`, let's not flag it again for the same message)
=> Automod invite filter updated regex

backend/src/plugins/Roles/commands/RemoveRoleCmd.ts
Fixes small typo in the `!removerole` command.
=> Fixed typo in !removerole

backend/src/plugins/Utility/commands/RolesCmd.ts
Current setup:
With this pr:
***
Why the current implementation is slow:
- It uses [`<Role>#members`](https://github.com/discordjs/discord.js/blob/stable/src/structures/Role.js#L139), which by itself uses [`<GuildMember>#roles#cache`](https://github.com/discordjs/discord.js/blob/stable/src/managers/GuildMemberRoleManager.js#L34)
=> perf: rolescmd with -counts option

backend/src/RecoverablePluginError.ts
I ran into this while testing. This error message gets thrown when the specified mute role is invalid, or when it is not valid. 
The previous error message of "not invalid" made no sense.
=> Fixed mute error message double negative

backend/src/plugins/Persist/events/LoadDataEvt.ts
Fixes the persist plugin attempting to check permissions for and assigning deleted roles.
=> Fix Persist assigning deleted roles

backend/src/data/GuildSavedMessages.ts, backend/src/plugins/Automod/AutomodPlugin.ts, backend/src/plugins/Automod/events/runAutomodOnThreadEvents.ts, backend/src/plugins/Automod/functions/runAutomod.ts, backend/src/plugins/Automod/triggers/availableTriggers.ts, backend/src/plugins/Automod/triggers/threadCreate.ts, backend/src/plugins/Automod/triggers/threadDelete.ts, backend/src/plugins/Automod/types.ts
Example config:
```yml
plugins:
automod: 
config:
rules:
on_thread_create:
triggers:
- thread_create: {}
actions:
alert:
channel: "705009450855039042"
text: "{matchSummary}"
on_thread_delete: 
triggers:
- thread_delete:
parent: "705009450855039042"
actions:
alert:
channel: "705009450855039042"
text: "{matchSummary}"
```
=> Added thread_create and thread_delete automod triggers

backend/src/plugins/Automod/triggers/matchAttachmentType.ts
=> chore: remove double parenthesis in match_attachment_type trigger

backend/src/plugins/Automod/actions/ban.ts, backend/src/plugins/ModActions/functions/banUserId.ts
- `actionConfig.deleteMessageDays || undefined` would incorrectly default `0` to `undefined`
- the range for delete_message_days is 0-7, not 0-30
=> fix: allow 0 deleteMessageDays and fix upper limit

backend/src/data/ApiLogins.ts
This PR is to allow long lived ApiKeys to be used in an automated deployment. This is mostly for self-hosted instances, but if a long lived ApiKey is created in the main host by Dragory, this allows it to be used for more than a day. Tested on the Splitgate Server host
=> Add check to refreshApiKeyExpiryTime to not refresh long lived keys

backend/src/utils.ts
There was a mismatch of types on zod and io-ts
https://github.com/ZeppelinBot/Zeppelin/blob/feeb0488556f10f6b02311476b32797dba314fa5/backend/src/utils.ts#L330
https://github.com/ZeppelinBot/Zeppelin/blob/feeb0488556f10f6b02311476b32797dba314fa5/backend/src/utils.ts#L269
This makes it fail to send tags with embeds that have `timestamp` configured on them since the embed is actually being validated with both
https://github.com/ZeppelinBot/Zeppelin/blob/feeb0488556f10f6b02311476b32797dba314fa5/backend/src/plugins/Tags/util/renderTagFromString.ts#L35
https://github.com/ZeppelinBot/Zeppelin/blob/feeb0488556f10f6b02311476b32797dba314fa5/backend/src/plugins/Tags/util/onMessageCreate.ts#L89
=> fix(tags): embed validation

backend/src/plugins/Automod/actions/availableActions.ts, backend/src/plugins/Automod/actions/changePerms.ts
adds server/role/member perm changing action.
does not REPLACE existing permissions for each object (roles/perm overwrites), but instead changes only the ones specified.
if `channel` is not provided, will default to serverwide perms, if a member's ID is provided in `target`, will silently fail if `channel` is not a valid channel.
There's probably some concern here or there for checking that the permissions we're changing doesn't end up being the same as what's already defined on discord's side, to save a few api calls, but I don't think this is a major issue, and I couldn't think of a super simple, clean and easy way to check this with this code.
@almeidx will probably roast me for it so I thought I'd mention it ahead of time just to mention that I did think of this problem.
samples: …
=> Automod add changeperms action

backend/src/plugins/Tags/commands/TagListCmd.ts
Resolves #347 
Improves the readability of the tag list by grouping tags by their first letter for easy scanning.
Additionally, adds the feature to filter tags based on the letters contained within the tag name, for example, the search "ts" would show results for tags named "ts", "test", "typescript", etc. as the letters appear in the tag name in the given order.
Note: this has only been tested on mock data, not an actual running instance.
Example:
=> feat: Tag list search and improved readability

backend/src/plugins/Utility/functions/getUserInfoEmbed.ts
Instead split the options into all four, from mute and deaf to selfMute, selfDeaf, serverMute and serverDeaf.
This should provide a lot more clarity.
=> Fix "Server voice muted" being true even if self-muted, misleading mods into thinking the user was right-click muted by a moderator

dashboard/src/components/PrivacyPolicy.vue
I'm aware that both links redirect to the same place, but this fix would allow Dragory to make a new repo called ZeppelinBot in the future (despite the unlikelyhood) whilst maintaining the functionality of the Privacy Policy.
=> Update Repo URL on Privacy Policy

backend/src/plugins/Tags/commands/TagListCmd.ts
This is a very minor change that will make search terms case-insensitive when using `!tags [search]` or `!tag list [search]`
For example, `!tag Example` would list tags that include the word `"example"` even though the search term has an uppercase E.
=> feat: Make tag list search case-insensitive

backend/src/plugins/Utility/functions/getServerInfoEmbed.ts
=> Display available emojis separately from total on server info

backend/src/data/Mutes.ts, backend/src/plugins/Mutes/MutesPlugin.ts, backend/src/plugins/Mutes/functions/muteUser.ts
Missing dependency currently causes a failure to unmute if RoleManager isnt loaded by anything otherwise
And timeout expiry of 28 days can cause a weird edge-case where timeouts will fail due to it being the same as the API limit, probably with time drift idk
=> Add missing dependency to mutes plugin & fix timeout expiry

backend/src/plugins/Automod/triggers/matchAttachmentType.ts
Discord attachment URLs now have a query string at the end
e.g. `https://cdn.discordapp.com/attachments/509738505241493515/1149102933129044079/zenyatta.jpg?ex=64fa4901&is=64f8f781&hm=f20463b7174e25f4bec8d1e6d7201275ebfd1ee62d11fe022b63429c4d4ac9f6&`
Fixes ZDEV-33
=> fix parsing of file extension in match_attachment_type trigger

backend/src/plugins/Automod/actions/setSlowmode.ts
(Fixes #275)
Now if `channels` is empty or undefined it will set slowmode on the current channel, in terms of functionality I don't think there's any downgrade or loss, however without proper documentation/awareness I imagine this will create issues down the line of people not knowing how this works, similarly to how many other things on the bot are as of right now.
This is mostly for compatibility with #272
=> Reworked automod "set_slowmode" action

backend/src/utils.ts
Fixes ZDEV-64
Fixes ZDEV-66
~~turns out im lazy. also i didnt want to touch the regex itself because i dont want to deal with potential new bypasses originated due to changing it. and it's also tricky since a non-encoded url can probably have `[]().` and still be valid~~
=> automod match_link fixes

backend/src/plugins/Automod/events/runAutomodOnAntiraidLevel.ts, backend/src/plugins/Automod/functions/setAntiraidLevel.ts, backend/src/plugins/Automod/triggers/antiraidLevel.ts, backend/src/plugins/Automod/types.ts
Right now, the automod trigger `antiraid_level` runs any time the antiraid level is updated, even if it's value isn't changing (for example, `high` -> `high`). This adds an option `only_on_change` to disable that behavior, making it only run the rule if the value is actually changing (`off` -> `high`, `low` -> `high`, NOT `high` -> `high`).
=> Add option to trigger antiraid_level only on change

dashboard/src/components/docs/Moderation.vue, dashboard/src/routes.ts
This guide aims to somewhat complete the currently WIP state of https://zeppelin.gg/docs/setup-guides/moderation .
Happy to implement more example tabs in corrospondence to the text under each header.
It focuses on the setup of the `mod_actions` plugin, but it can be extended to focus on the command side too.
=> Moderation Guide

backend/package-lock.json, backend/package.json
discord.js no longer uses erlpack internally, so its dependency can be removed.
=> remove erlpack

backend/src/plugins/Persist/PersistPlugin.ts, backend/src/plugins/Persist/events/StoreDataEvt.ts, backend/src/plugins/availablePlugins.ts
Until we figure out what to do with ZDEV-107, let's atleast not subject selfhosters to this
=> fix: Disable guildMemberCache plugin temporarily

backend/src/plugins/ModActions/commands/CasesModCmd.ts, backend/src/plugins/ModActions/commands/CasesUserCmd.ts
Solves:
* Consistent member/mod cases-per-page limit
* Fix inconsistency with lastCaseNum using page boundary limits on last page rather than total cases
Fixes [ZDEV-45](https://linear.app/zeppelinbot/issue/ZDEV-45), [ZDEV-46](https://linear.app/zeppelinbot/issue/ZDEV-46)
Supersedes #431
=> Some fixes to !cases (continued)

docker-compose.lightweight.yml
Fixes depends_on in the lightweight version of the docker-compose as its not using a db inside the compose stack
=> Fixes depends_on mysql

docker-compose.lightweight.yml
Working_dir was fixed in the docker-compose standalone but not in the lightweight version
=> Fixing docker-compose lightweight migration workking_dir

docs/DEVELOPMENT.md
Accidental typo here, the plugin is called 'Dev Containers' not 'Remote - Containers' which is used in the second option for creating the bot.
=> 🔧 Typo VSCode Container Plugin

backend/src/api/guilds/importExport.ts
Recently I noticed that after importing case data the message links are no longer in the embed to jump to a specific case. The reason for this is that log_message_id is missing when exporting the case data, which is why all the previous message links were no longer available.
=> Add log_message_id to export cases

backend/src/plugins/Counters/types.ts
It appears that the trigger name is "triggers" instead of the actual AutoMod rule name.
**Example**: ["counters", "nsfw_infractions", "triggers", "autoban", "condition"]
ctx.path.length - 2 returns "triggers" while it should be ctx.path.length -1 for the automod rule name.
=> fix: wrong key for counter's counter_trigger rule name

backend/src/plugins/ModActions/commands/ban/BanMsgCmd.ts, backend/src/plugins/ModActions/commands/ban/BanSlashCmd.ts
Pass the `delete-days` arg from `BanMsgCmd` to `actualBanCmd`
=> fix: delete-days not applied when banning

backend/src/plugins/ModActions/commands/deletecase/actualDeleteCaseCmd.ts
updates the `actualDeleteCaseCmd` function to use button-based confirmation instead of relying on text input (yes/no) for case deletions
=> Replace text confirmation with button-based confirmation in delete case command

backend/src/plugins/ModActions/commands/addcase/AddCaseSlashCmd.ts
Fixes numeric enum values showing in `/addcase` options by filtering `Object.keys(CaseTypes)` to exclude reverse mappings.
=> Fix: Filter numeric enum keys from case type slash command options
