ZeppelinBot/Zeppelin

- src/plugins/CompanionChannels.ts
- src/plugins/availablePlugins.ts
Channels are configured in the servers config file
> Added companion channel functionality

- src/plugins/Mutes.ts
Usefull, because otherwise you do not know if you did the command right on large servers (Because it takes forever to load). Do not want the command to be executed twice on accident
> Implemented loading and finished message for the mutes command

- src/PluginRuntimeError.ts
- src/data/GuildVCAlerts.ts
- src/data/entities/VCAlert.ts
- src/migrations/1561391921385-AddVCAlertTable.ts
- src/plugins/LocateUser.ts
- src/plugins/availablePlugins.ts
Basically alerts from MRVN, but this time with duration in nice format (2h30m) and reminders (because you can now potentially make an alert for 1 year and forget it exists, so you get reminded of what it was for.
Also where is there too.
With migrate and everything
> Fully functional LocatePlugin with alerts in DB and reminders

- backend/src/plugins/SelfGrantableRolesPlugin.ts
Added config that mentions roles by Id instead of name in the self assignable roles success messages
> Role mentions for self assignable role plugin

- backend/src/plugins/ModActions.ts
- backend/src/plugins/Mutes.ts
The unmute command can now unmute users who have had the mute role manually applied to them
> Remove manual mutes

- backend/src/plugins/Automod/Automod.ts
- backend/src/plugins/Automod/types.ts
Intended to allow certain channels (i.e. bug reporting ones) to only allow .log files with uploads enabled, making it impossible to upload mp4s to troll or similar
> Added ability to white or blacklist attachment filetype in automod

- backend/src/data/GuildVCAlerts.ts
- backend/src/data/entities/VCAlert.ts
- backend/src/migrations/1580654617890-AddActiveFollowsToLocateUser.ts
- backend/src/plugins/LocateUser.ts
Also added descriptions and examples to the commands in the documentation.
Requires running a DB migration
> Made Alerts infinite until timed out, added -active and changed command signature

- backend/src/plugins/Utility.ts
Support for things marked green here: [image](https://daark.de/sk07M) and emoji names
> Enable checking for emoji, asset text and details when using -ss

- backend/src/plugins/ModActions.ts
- Added `-clean` option, kicking the user and then removing the last day of messages
- Replaced softbans implementation with a call to kick and a deprecation warning
> Add an argument to kick to allow cleaning the last 1d of messages

- backend/src/plugins/Utility.ts
A command that allows users to search for banned users
> Ban search

- backend/src/plugins/LocateUser/commands/FollowCmd.ts
Dont know how this didnt explode in testing
> [K30] LocateUser: Change rest to catchAll

- .gitignore
- backend/src/plugins/Logs/LogsPlugin.ts
- backend/src/plugins/Logs/events/LogsChannelModifyEvts.ts
- backend/src/plugins/Logs/events/LogsGuildBanEvts.ts
- backend/src/plugins/Logs/events/LogsGuildMemberAddEvt.ts
- backend/src/plugins/Logs/events/LogsGuildMemberRemoveEvt.ts
- backend/src/plugins/Logs/events/LogsRoleModifyEvts.ts
- backend/src/plugins/Logs/events/LogsUserUpdateEvts.ts
- backend/src/plugins/Logs/events/LogsVoiceChannelEvts.ts
- backend/src/plugins/Logs/types.ts
- backend/src/plugins/Logs/util/getLogMessage.ts
- backend/src/plugins/Logs/util/log.ts
- backend/src/plugins/Logs/util/onMessageDelete.ts
- backend/src/plugins/Logs/util/onMessageDeleteBulk.ts
- backend/src/plugins/Logs/util/onMessageUpdate.ts
- backend/src/plugins/availablePlugins.ts
Also change `logs` to `/logs` in root .gitignore so we dont ignore the plugin
> [K30] Migrated Logs

- backend/src/plugins/LocateUser/commands/FollowCmd.ts
- backend/src/plugins/ModActions/commands/ForcemuteCmd.ts
- backend/src/plugins/Mutes/MutesPlugin.ts
- backend/src/plugins/Mutes/events/ClearActiveMuteOnMemberBanEvt.ts
- backend/src/plugins/Mutes/events/ReapplyActiveMuteOnJoinEvt.ts
- backend/src/plugins/Post/commands/PostEmbedCmd.ts
- backend/src/plugins/Reminders/commands/RemindersDeleteCmd.ts
change -active option on locateuser/follow to be a switch
> [K30] Various Fixes for K30

- backend/src/data/GuildNicknameHistory.ts
> [K30] Change nickname storage to the intended 10

- backend/src/plugins/Utility/commands/CleanCmd.ts
Suggestion https://canary.discordapp.com/channels/473085256233123841/534711895803035648/715118036142784522
> Post a message letting the mod know we are now cleaning

- backend/src/plugins/Utility/UtilityPlugin.ts
- backend/src/plugins/Utility/actualInfoCmd.ts
- backend/src/plugins/Utility/commands/InfoCmd.ts
- backend/src/plugins/Utility/search.ts
- backend/src/plugins/Utility/types.ts
> Load expanded !info if there is only one result in !search

- backend/src/data/DefaultLogMessages.json
- backend/src/data/LogType.ts
- backend/src/plugins/ModActions/ModActionsPlugin.ts
- backend/src/plugins/ModActions/commands/MassmuteCmd.ts
- backend/src/plugins/ModActions/types.ts
Same as #35 but, you guessed it, updated
> Update Massmute to newest version... again

- backend/src/plugins/CompanionChannels/events/VoiceChannelJoinEvt.ts
- backend/src/plugins/CompanionChannels/events/VoiceChannelLeaveEvt.ts
- backend/src/plugins/CompanionChannels/events/VoiceChannelSwitchEvt.ts
- backend/src/plugins/CompanionChannels/functions/getCompanionChannelOptsForVoiceChannelId.ts
- backend/src/plugins/CompanionChannels/functions/handleCompanionPermissions.ts
Needed for categories that get new VCs randomly but should have companion channels
> Allow companion_channels to take category ID

- backend/src/plugins/ModActions/commands/DeleteCaseCmd.ts
- backend/src/plugins/ModActions/commands/HideCaseCmd.ts
- backend/src/plugins/ModActions/commands/UnhideCaseCmd.ts
Request https://canary.discord.com/channels/473085256233123841/534711895803035648/752785710632665188
> Allow hidecase, unhidecase and deletecase to take multiple case numbers

- backend/src/plugins/Utility/commands/CleanCmd.ts
> make !clean ignore pins by default, explicit -delete-pins | -p option to delete them

- backend/src/data/DefaultLogMessages.json
- backend/src/plugins/Logs/util/onMessageDeleteBulk.ts
This makes searching for deleted messages by a certain User ID a lot easier using discords built in search function
> List Message Author IDs in Bulk Deletes Logs

- backend/src/plugins/ReactionRoles/commands/InitReactionRolesCmd.ts
reactionRolePairs confuses a lot of people, as the documentation for it is nonexistent
> Add example of reaction_roles command to documentation

- backend/src/data/DefaultLogMessages.json
- backend/src/data/LogType.ts
- backend/src/plugins/ModActions/ModActionsPlugin.ts
- backend/src/plugins/ModActions/commands/MassUnbanCmd.ts
- backend/src/plugins/ModActions/types.ts
Feedback/Improvement ideas wanted, i feel as if im missing a good way to improve this codes readability and execution time but i cant figure it out right now.
> Add working massunban command

- backend/src/plugins/Logs/LogsPlugin.ts
- backend/src/plugins/Logs/types.ts
- backend/src/plugins/Logs/util/getLogMessage.ts
- backend/src/plugins/Logs/util/log.ts
- backend/src/utils.ts
Optionally you can return to old behavior by setting allow_user_mentions to true
> Disable mentions in logs, allowing mods to be mentioned

- backend/src/plugins/Utility/commands/CleanCmd.ts
https://canary.discord.com/channels/473085256233123841/534711895803035648/760160134751060028
But slightly modified
Clean <count> amount of messages unless the messages are older than the specified ID
> Allow clean to hard stop at a certain ID

- backend/src/utils.ts
Fixes https://canary.discord.com/channels/473085256233123841/534722948246929429/807111252131315772
> Add newline after ``` so single words dont get seen as language

- backend/src/plugins/Utility/UtilityPlugin.ts
- backend/src/plugins/Utility/commands/ChannelInfoCmd.ts
- backend/src/plugins/Utility/commands/InfoCmd.ts
- backend/src/plugins/Utility/commands/InviteInfoCmd.ts
- backend/src/plugins/Utility/commands/MessageInfoCmd.ts
- backend/src/plugins/Utility/commands/ServerInfoCmd.ts
Fixed !info not checking for any of the sub-permissions
Fixed message/channel/invite checking non-existent permissions
Fixed ServerCmd being out of line with the rest of the info commands name-wise
> Fix various issues with the info commands

- backend/src/data/GuildMutes.ts
- backend/src/data/entities/Mute.ts
- backend/src/migrations/1608608903570-CreateRestoredRolesColumn.ts
- backend/src/plugins/Automod/actions/mute.ts
- backend/src/plugins/Mutes/MutesPlugin.ts
- backend/src/plugins/Mutes/functions/clearExpiredMutes.ts
- backend/src/plugins/Mutes/functions/muteUser.ts
- backend/src/plugins/Mutes/functions/unmuteUser.ts
- backend/src/plugins/Mutes/types.ts
- backend/src/plugins/Spam/types.ts
- backend/src/plugins/Spam/util/logAndDetectMessageSpam.ts
- backend/src/plugins/Spam/util/logAndDetectOtherSpam.ts
All credit goes to @roflmaoqwerty, i merely updated it to work with the new version due to time constraints on his side.
Originally PR #61
> Allow certain or all roles to be removed upon mute and readded on unmute

- backend/src/plugins/ModActions/commands/UpdateCmd.ts
Adds `!reason` & `!addnote` to the current `!update` command.
> Added aliases for UpdateCmd

- backend/src/plugins/Starboard/StarboardPlugin.ts
- backend/src/plugins/Starboard/types.ts
- backend/src/plugins/Starboard/util/createStarboardEmbedFromMessage.ts
- backend/src/plugins/Starboard/util/saveMessageToStarboard.ts
This time I didn't screw up merge stuff :), PR is as simple as it sounds, just added color stuff, tested and working
> feat: add color option to starboard

- backend/src/plugins/Utility/commands/AvatarCmd.ts
> Add !av as alias to !avatar

- backend/src/plugins/Automod/info.ts
Old message_spam
corrected it to 
emoji_spam
> Typo in automod docs

- backend/src/plugins/Counters/commands/SetCounterCmd.ts
Use isNaN check so 0 can be accepted but still restrict to only numbers
> BugFix Correct NaN check in setcounter

- backend/src/plugins/Reminders/commands/RemindCmd.ts
!reminder as an additional alias
> Alias for remind command

- backend/src/plugins/ModActions/commands/CasesModCmd.ts
> Added additional alias for cases

- backend/ormconfig.js
- backend/src/migrations/1573158035867-AddTypeAndPermissionsToApiPermissions.ts
- backend/src/plugins/Cases/functions/postToCaseLogChannel.ts
- backend/src/plugins/Censor/util/censorMessage.ts
- backend/src/plugins/ChannelArchiver/rehostAttachment.ts
- backend/src/plugins/LocateUser/utils/moveMember.ts
- backend/src/plugins/LocateUser/utils/sendWhere.ts
- backend/src/plugins/MessageSaver/saveMessagesToDB.ts
- backend/src/plugins/ModActions/commands/ForcebanCmd.ts
- backend/src/plugins/ModActions/commands/MassBanCmd.ts
- backend/src/plugins/ModActions/commands/MassUnbanCmd.ts
- backend/src/plugins/ModActions/commands/UnbanCmd.ts
- backend/src/plugins/ModActions/functions/actualKickMemberCmd.ts
- backend/src/plugins/Mutes/functions/clearExpiredMutes.ts
- backend/src/plugins/Mutes/functions/muteUser.ts
- backend/src/plugins/Post/util/scheduledPostLoop.ts
- backend/src/plugins/Reminders/utils/postDueRemindersLoop.ts
- backend/src/plugins/SelfGrantableRoles/commands/RoleAddCmd.ts
- backend/src/plugins/SelfGrantableRoles/commands/RoleRemoveCmd.ts
- backend/src/plugins/Slowmode/util/disableBotSlowmodeForChannel.ts
- backend/src/plugins/Starboard/events/StarboardReactionAddEvt.ts
- backend/src/plugins/Utility/commands/AboutCmd.ts
- backend/src/plugins/Utility/commands/NicknameCmd.ts
- backend/src/plugins/Utility/commands/NicknameResetCmd.ts
- backend/src/plugins/Utility/commands/VcdisconnectCmd.ts
- backend/src/plugins/Utility/commands/VcmoveCmd.ts
- backend/src/plugins/WelcomeMessage/events/SendWelcomeMessageEvt.ts
- backend/src/utils.ts
- dashboard/src/store/auth.ts
Removed unused exception variables from `try..catch`es
> refactor(*): removed unused exception variables

- backend/src/plugins/Utility/functions/getChannelInfoEmbed.ts
> Properly support Stage Channels on ChannelInfoCmd

- backend/src/plugins/Utility/commands/EmojiInfoCmd.ts
- backend/src/plugins/Utility/commands/InfoCmd.ts
- backend/src/plugins/Utility/functions/getCustomEmojiId.ts
> Added support for snowflakes on EmojiInfoCmd

- README.md
Updated readme to show prefix as part of the example config
> Updated Readme (example config)

- backend/src/plugins/SelfGrantableRoles/commands/RoleAddCmd.ts
- backend/src/plugins/SelfGrantableRoles/commands/RoleRemoveCmd.ts
> Made RoleAddCmd and RoleRemoveCmd mention the command author

- backend/src/plugins/Automod/AutomodPlugin.ts
- backend/src/plugins/Automod/functions/runAutomod.ts
- backend/src/plugins/Automod/types.ts
This essentially makes it so you can run multiple rules at once
> Added `allow_further_rules` option to automod rules

- backend/src/plugins/Utility/commands/NicknameCmd.ts
- backend/src/plugins/Utility/commands/NicknameResetCmd.ts
- backend/src/utils.ts
Also added a check to see if the member has a nickname before resetting on the nickname reset command
> Made the nickname argument optional on nickname command

- backend/src/api/docs.ts
- backend/src/plugins/Censor/CensorPlugin.ts
- backend/src/plugins/Spam/SpamPlugin.ts
- backend/src/plugins/ZeppelinPluginBlueprint.ts
- backend/src/types.ts
- dashboard/src/components/docs/DocsLayout.vue
LMK if there are any other legacy plugins
> docs: Added legacy plugins section

- backend/src/plugins/Automod/events/RunAutomodOnMemberUpdate.ts
This issue was pointed out by @metal0
> fix: automod on guildMemberUpdate

- backend/src/plugins/CustomEvents/CustomEventsPlugin.ts
- backend/src/plugins/CustomEvents/actions/addRoleAction.ts
Fixes custom events unsafe values crashing the bot and adds a sanitization check to addRoleAction for existing roles
> Custom Events fixes

- backend/src/templateFormatter.ts
Not entirely sure about the round function, I'm sure @almeidx will provide some very helpful comments though
> template fns - add strlen and rounding

- backend/src/plugins/Starboard/events/StarboardReactionAddEvt.ts
- backend/src/plugins/Starboard/events/StarboardReactionRemoveEvts.ts
- backend/src/plugins/Starboard/util/removeMessageFromStarboard.ts
I tested pretty much every use-case for starboard and couldn't get it to error out after just the fix to the message deletion
I don't expect you to merge this, code is not very clean and needs a cleanup script still, just wanted to let you know what the starboard issues were (not that they were very hard to track down but w/e)
@almeidx spare me with the code reviews 🙏 i know this doesnt look good 🙏
> Starboard first-pass fix

- backend/src/data/GuildSavedMessages.ts
- backend/src/plugins/Automod/constants.ts
- backend/src/plugins/Automod/events/runAutomodOnThreadEvents.ts
- backend/src/plugins/Automod/triggers/availableTriggers.ts
- backend/src/plugins/Automod/triggers/threadCreateSpam.ts
~~Depends on #272~~
Example config:
```yml
plugins:
automod: 
config:
rules:
thread_spam:
triggers:
- thread_create_spam:
within: 30s
amount: 3
actions:
alert:
channel: "705009450855039042"
text: "spam bruh"
```
> Added thread_create_spam automod trigger

- backend/src/plugins/Tags/TagsPlugin.ts
- backend/src/plugins/Tags/docs.ts
- backend/src/plugins/Tags/templateFunctions.ts
- backend/src/plugins/Tags/types.ts
Documents the template functions.
As requested by @Dragory , this is temporarily associated with the Tags plugin for the purpose of later generating this dynamically.
This could **REALLY** use an expandable, but I have no clue how to do it via markdown.
For any changes regarding formatting please just change it yourself on the PR instead of commenting if you have the time.. thanks ~~looking at you @Almeidx~~
> Docs - Document template functions

- backend/src/plugins/Utility/functions/getUserInfoEmbed.ts
move along, nothing to see here
> fix: negative number in userinfo command

- PRODUCTION.md
Fixes the order of the flags so that the command works
> Change order of flags in command

- backend/src/plugins/Cases/functions/getCaseEmbed.ts
Can someone test this PR ? thx
> Fix codeblocks case history quote markdown

- backend/src/plugins/ModActions/commands/CasesUserCmd.ts
I was forced to make this pull request[.](https://discord.com/channels/473085256233123841/534722948246929429/986007419983388672)
> fix: no response if user only has hidden cases in `!cases @user`

- backend/src/plugins/Automod/actions/setCounter.ts
- backend/src/plugins/Counters/functions/setCounterValue.ts
> Fix counters set_value not defaulting nulls if not using per_user/per_channel

- backend/src/data/GuildCounters.ts
> fix: typeorm counters missing "where" from new typeorm update

- backend/src/data/GuildCounters.ts
- package.json
Globs surrounded with `'` do not work in Windows.
> fix formatting and globs in package.json

- backend/src/api/guilds.ts
> API: Don't allow users removing themselves

- docker-compose.production.yml
> compose: Don't expose MySQL through all interfaces

- backend/src/plugins/Automod/triggers/matchWords.ts
Added a missing closing bracket for the regex to work.
> Fix loose matching for automod

- backend/src/plugins/Mutes/functions/clearMute.ts
> logs: implement MEMBER_MUTE_EXPIRED

- backend/src/plugins/ModActions/events/AuditLogEvents.ts
https://discord.com/channels/473085256233123841/534722948246929429/1199365086482022480
> fix case note on timeout expiration for manual timeouts

- backend/src/data/DefaultLogMessages.json
- backend/src/plugins/Automod/actions/alert.ts
- backend/src/plugins/Automod/actions/log.ts
- backend/src/plugins/Automod/functions/runAutomod.ts
- backend/src/plugins/Automod/helpers.ts
- backend/src/plugins/Automod/types.ts
- backend/src/plugins/Logs/logFunctions/logAutomodAction.ts
> feat: pretty_name for automod

- backend/src/index.ts
- backend/src/migrations/1573248462469-MoveStarboardsToConfig.ts
- backend/src/migrations/1596994103885-AddCaseNotesForeignKey.ts
- backend/src/migrations/1597015567215-AddLogMessageIdToCases.ts
- backend/src/migrations/1597109357201-CreateMemberTimezonesTable.ts
- backend/src/migrations/1617363975046-UpdateCounterTriggers.ts
- backend/src/plugins/Censor/util/applyFiltersToMsg.ts
- backend/src/plugins/GuildConfigReloader/types.ts
- backend/src/plugins/GuildMemberCache/types.ts
- backend/src/plugins/InternalPoster/types.ts
- backend/src/plugins/Logs/LogsPlugin.ts
- backend/src/plugins/Logs/logFunctions/logMessageDelete.ts
- backend/src/plugins/Logs/types.ts
- backend/src/plugins/Logs/util/getLogMessage.ts
- backend/src/plugins/MessageSaver/MessageSaverPlugin.ts
- backend/src/plugins/ModActions/commands/CasesUserCmd.ts
- backend/src/plugins/ModActions/functions/kickMember.ts
- backend/src/plugins/ModActions/functions/warnMember.ts
- backend/src/plugins/Phisherman/functions/getDomainInfo.ts
- backend/src/templateFormatter.test.ts
- backend/src/utils.ts
> chore: format repo

- backend/src/plugins/Automod/triggers/matchWords.ts
The current loose matching implementation creates too many false positives because it allows any characters between letters of filtered words. For example, filtering "hello" could incorrectly match "habcelldefgo".
- Restricted loose matching to only whitespace and common separator characters (`[\\s\\-_.,!?]`)
- Fixed word boundary handling for loose matching patterns
- Now returns the actual matched text instead of empty string
- Added proper capture groups to identify which word triggered the match
> Fix loose matching false positives in MatchWordsTrigger
